core/urls.py
from django.urls import path
from .import views

app_name = 'core'

urlpatterns = [
    path('', views.home, name='home'),
    path('article/int:article/', views.article_detail, name='article_detail'),
    path('forum/', views.forum, name='forum'),
    path("signup/", views.signup, name="signup"),
    path("post/", views.post, name="post"),
]

health/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Article(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

class ForumPost(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    image = models.ImageField(upload_to="images")
    def __str__(self):
        return self.title

class Comment(models.Model):
    post = models.ForeignKey(ForumPost, related_name="comments", on_delete=models.CASCADE)
    content = models.TextField
    created_at = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'comment by {self.author} on {self.post}'

core/forms.py
from django import forms

from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]

    username = forms.CharField(widget=forms.TextInput(attrs={"placeholder": "Enter Username", "class": "form-control"}))
    email = forms.CharField(widget=forms.EmailInput(attrs={"placeholder": "Enter Email","class": "form-control"}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={"placeholder": "Enter Password","class": "form-control"}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={"placeholder": "Repeat Password","class": "form-control"}))

core/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Article, ForumPost
from .forms import RegistrationForm
# Create your views here.

def home(request):
    articles = Article.objects.all()
    context = {'articles':articles}
    return render(request, 'core/home.html', context)

def post(request):
    articles = Article.objects.all()
    context = {'articles': articles}
    return render(request, 'core/post.html', context)


def article_detail(request):
    article = get_object_or_404(Article)
    context = {'article': article}
    return render(request, 'core/article_detail.html',context)

def forum(request):
    posts = ForumPost.objects.all()
    context = {'posts',posts}
    return render(request, 'core/forum.html', context)


def signup(request):

    if request.method == "POST":
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            return render("core:home")
    else:
        form = RegistrationForm

    context = {"form": form}
    return render(request, "core/signup.html", context)

templates/core/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Menat Health</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  </head>
  <body>

    <nav class="navbar navbar-expand-lg bg-success navbar-dark">
  <div class="container-fluid container">
    <a class="navbar-brand" href="#">Mental Health</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mx-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'core:home' %}">Home</a>
        </li>
         <li class="nav-item">
           <a class="nav-link active" aria-current="page" href="{% url 'core:post' %}">Post</a>
         </li>
         <li class="nav-item">
           <a class="nav-link active" aria-current="page" href="{% url 'core:signup' %}">Signup</a>
         </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
    </div>
 </nav>
    <div class="container">
       {% block content %}
       {% endblock content %}
    </div>



    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

templates/core/home.html
{% extends 'core/base.html' %}

{% block title %}Home{% endblock title %}

 ec>
       <img src="templates/core/download (36).jpeg" alt="">
   </div>


templates/core/post.html
{% extends 'core/base.html' %}

{% block title %}Post{% endblock title %}

{% block content %}
<div class="row">
    {% for article in articles %}
        <div class="col">
        <div class="card" style="width: 18rem; margin-top: 10px;">

            <div class="card-body">
                <div><strong>{{ article.title }}</strong></div>
                <small>Written by: {{ article.author }}</small>
                <hr>
                <a href="{% url 'core:post' %}" class="btn btn-primary">Read</a>
            </div>
        </div>
    </div>

    {% endfor %}
</div>
{% endblock content %}

templates/core/signup.html
{% extends "core/base.html" %}
{% block title %}Signup{% endblock title %}
{% block content %}
    <h1>Signup</h1>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Send</button>
    </form>
{% endblock content %}